@testset "generated-module contract and docstrings" begin
    paths = OpenAPI.obj(
        "/pets/{petId}" => OpenAPI.obj(
            "get" => OpenAPI.obj(
                "operationId" => "getPet",
                "parameters" => Any[
                    OpenAPI.obj(
                        "name" => "petId",
                        "in" => "path",
                        "required" => true,
                        "description" => "Numeric pet identifier.",
                        "schema" => OpenAPI.obj("type" => "integer"),
                    ),
                ],
                "responses" => OpenAPI.obj(
                    "200" => OpenAPI.obj(
                        "description" => "ok",
                        "content" => OpenAPI.obj(
                            "application/json" => OpenAPI.obj(
                                "schema" => OpenAPI.obj(
                                    "\$ref" => "#/components/schemas/Pet",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
    document = minimal_openapi("3.1.1", paths)
    document["components"] = OpenAPI.obj(
        "schemas" => OpenAPI.obj(
            "Pet" => OpenAPI.obj(
                "type" => "object",
                "description" => "A pet in the store.",
                "required" => Any["name"],
                "properties" => OpenAPI.obj(
                    "name" => OpenAPI.obj(
                        "type" => "string",
                        "description" => "The pet's display name.",
                    ),
                    "tag" => OpenAPI.obj("type" => "string"),
                    "status" => OpenAPI.obj(
                        "\$ref" => "#/components/schemas/Status",
                    ),
                ),
            ),
            "Status" => OpenAPI.obj(
                "type" => "string",
                "description" => "Adoption status.",
                "enum" => Any["available", "adopted"],
            ),
        ),
    )

    client_source = OpenAPI.client(document; name = "ContractClient")
    server_source = OpenAPI.server(document; name = "ContractServer")
    guard = string(
        "Runtime.require_contract(",
        OpenAPI.Runtime.CONTRACT_VERSION,
        ", ",
        repr(OpenAPI.PACKAGE_VERSION),
        ")",
    )

    @testset "version stamp and load-time guard" begin
        banner = "# Generated by OpenAPI.jl v" * OpenAPI.PACKAGE_VERSION * " from "
        @test startswith(client_source, banner)
        @test startswith(server_source, banner)
        @test occursin(guard, client_source)
        @test occursin(guard, server_source)

        current = OpenAPI.Runtime.CONTRACT_VERSION
        @test OpenAPI.Runtime.require_contract(current, OpenAPI.PACKAGE_VERSION) === nothing
        mismatch = try
            OpenAPI.Runtime.require_contract(current + 1, "0.0.0")
            nothing
        catch error
            error
        end
        @test mismatch isa ErrorException
        message = sprint(showerror, mismatch)
        @test occursin("produced by OpenAPI.jl v0.0.0", message)
        @test occursin("contract $(current + 1)", message)
        @test occursin("provides contract $current", message)
        @test occursin("regenerate", message)
    end

    @testset "dialects are emitted by name, never positionally" begin
        @test occursin("SchemaEngine.dialect(:", client_source)
        @test !occursin("SchemaEngine.Dialect(", client_source)
        @test occursin("SchemaEngine.dialect(:", server_source)
        @test !occursin("SchemaEngine.Dialect(", server_source)

        # the keyword constructor used for vocabulary-customized dialects
        # reconstructs a dialect exactly
        d = SchemaEngine.DRAFT202012
        @test SchemaEngine.Dialect(;
            name = d.name,
            uri = d.uri,
            id_keyword = d.id_keyword,
            ref_siblings = d.ref_siblings,
            modern_items = d.modern_items,
            unevaluated = d.unevaluated,
            dynamic_refs = d.dynamic_refs,
            recursive_refs = d.recursive_refs,
            applicator = d.applicator,
            validation = d.validation,
        ) === d
    end

    @testset "model and field docstrings from spec descriptions" begin
        pet_doc = "    Pet\n\nA pet in the store.\n\n" *
                  "- `name`: The pet's display name.\n- `status`: Adoption status."
        @test occursin("@doc " * repr(pet_doc), client_source)
        @test occursin("@doc " * repr("    Status\n\nAdoption status."), client_source)
        @test occursin("@doc " * repr(pet_doc), server_source)

        operation_doc = "    getpet(...)\n\n`GET /pets/{petId}`\n\n" *
                        "- `petid`: Numeric pet identifier."
        @test occursin("@doc " * repr(operation_doc), client_source)

        host = Module(:ContractDocsHost)
        Base.include_string(host, client_source, "ContractClient.jl")
        C = Base.invokelatest(getfield, host, :ContractClient)
        binding = Base.invokelatest(Base.Docs.Binding, C, :Pet)
        meta = Base.invokelatest(Base.Docs.meta, C)
        @test haskey(meta, binding)
        attached = join(
            (string(text) for docstr in values(meta[binding].docs)
             for text in docstr.text),
            "\n",
        )
        @test occursin("A pet in the store.", attached)
        @test occursin("The pet's display name.", attached)
    end
end
