@testset "generated-module contract and docstrings" begin
    paths = OpenAPI.obj(
        "/pets/{petId}" => OpenAPI.obj(
            "get" => OpenAPI.obj(
                "operationId" => "getPet",
                "parameters" => Any[
                    OpenAPI.obj(
                        "name" => "petId",
                        "in" => "path",
                        "required" => true,
                        "description" => "Numeric pet identifier.",
                        "schema" => OpenAPI.obj("type" => "integer"),
                    ),
                ],
                "responses" => OpenAPI.obj(
                    "200" => OpenAPI.obj(
                        "description" => "ok",
                        "content" => OpenAPI.obj(
                            "application/json" => OpenAPI.obj(
                                "schema" => OpenAPI.obj(
                                    "\$ref" => "#/components/schemas/Pet",
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
    document = minimal_openapi("3.1.1", paths)
    document["components"] = OpenAPI.obj(
        "schemas" => OpenAPI.obj(
            "Pet" => OpenAPI.obj(
                "type" => "object",
                "description" => "A pet in the store.",
                "required" => Any["name"],
                "properties" => OpenAPI.obj(
                    "name" => OpenAPI.obj(
                        "type" => "string",
                        "description" => "The pet's display name.",
                    ),
                    "tag" => OpenAPI.obj("type" => "string"),
                    "status" => OpenAPI.obj(
                        "\$ref" => "#/components/schemas/Status",
                    ),
                ),
            ),
            "Status" => OpenAPI.obj(
                "type" => "string",
                "description" => "Adoption status.",
                "enum" => Any["available", "adopted"],
            ),
        ),
    )

    client_source = OpenAPI.client(document; name = "ContractClient")
    server_source = OpenAPI.server(document; name = "ContractServer")
    guard = string(
        "Runtime.require_contract(",
        OpenAPI.Runtime.CONTRACT_VERSION,
        ", ",
        repr(OpenAPI.PACKAGE_VERSION),
        ")",
    )

    @testset "version stamp and load-time guard" begin
        banner = "# Generated by OpenAPI.jl v" * OpenAPI.PACKAGE_VERSION * " from "
        @test startswith(client_source, banner)
        @test startswith(server_source, banner)
        @test occursin(guard, client_source)
        @test occursin(guard, server_source)
        for source in (client_source, server_source)
            guard_position = findfirst(guard, source)
            import_position = findfirst("import OpenAPI.Runtime:", source)
            @test guard_position !== nothing
            @test import_position !== nothing
            @test first(guard_position) < first(import_position)
        end

        direct_server_source = OpenAPI.server_module_source(
            OpenAPI.serverplan(document; name = "DirectContractServer");
            imports = "using OpenAPI, JSON",
            glue = "",
        )
        @test occursin(guard, direct_server_source)
        @test first(findfirst(guard, direct_server_source)) <
              first(findfirst("import OpenAPI.Runtime:", direct_server_source))

        current = OpenAPI.Runtime.CONTRACT_VERSION
        @test current == 2
        @test OpenAPI.Runtime.require_contract(current, OpenAPI.PACKAGE_VERSION) === nothing
        for generated_contract in (1, current + 1)
            mismatch = try
                OpenAPI.Runtime.require_contract(generated_contract, "0.0.0")
                nothing
            catch error
                error
            end
            @test mismatch isa ErrorException
            message = sprint(showerror, mismatch)
            @test occursin("produced by OpenAPI.jl v0.0.0", message)
            @test occursin("contract $generated_contract", message)
            @test occursin("provides contract $current", message)
            @test occursin("regenerate", message)
        end
    end

    @testset "dialects are emitted by name, never positionally" begin
        for name in sort!(collect(keys(SchemaEngine.DIALECTS)))
            @test OpenAPI._dialect_literal(SchemaEngine.dialect(name)) ==
                  "SchemaEngine.dialect(" * repr(name) * ")"
        end
        @test occursin("SchemaEngine.dialect(:", client_source)
        @test !occursin(r"SchemaEngine\.Dialect\((?!;)", client_source)
        @test occursin("SchemaEngine.dialect(:", server_source)
        @test !occursin(r"SchemaEngine\.Dialect\((?!;)", server_source)
    end

    @testset "custom vocabulary dialects round-trip through generated modules" begin
        dialect_uri = "https://example.test/dialect/no-validation"
        metaschema = OpenAPI.obj(
            "\$schema" => SchemaEngine.DRAFT202012.uri,
            "\$id" => dialect_uri,
            "\$vocabulary" => OpenAPI.obj(
                "https://json-schema.org/draft/2020-12/vocab/core" => true,
            ),
        )
        custom_document = minimal_openapi(
            "3.1.1",
            OpenAPI.obj(
                "/value" => OpenAPI.obj(
                    "get" => OpenAPI.obj(
                        "operationId" => "getValue",
                        "responses" => OpenAPI.obj(
                            "200" => OpenAPI.obj(
                                "description" => "value",
                                "content" => OpenAPI.obj(
                                    "application/json" => OpenAPI.obj(
                                        "schema" => OpenAPI.obj(
                                            "type" => "integer",
                                            "minimum" => 10,
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        )
        custom_document["jsonSchemaDialect"] = dialect_uri
        retriever = OpenAPI.Resources.MemoryRetriever(
            Dict(dialect_uri => JSON.json(metaschema)),
        )
        generated = (
            OpenAPI.client(
                custom_document;
                name = "CustomDialectClient",
                allow_remote_refs = true,
                retriever,
            ) => :CustomDialectClient,
            OpenAPI.server(
                custom_document;
                name = "CustomDialectServer",
                allow_remote_refs = true,
                retriever,
            ) => :CustomDialectServer,
        )
        for (source, module_name) in generated
            @test occursin("SchemaEngine.Dialect(;", source)
            @test !occursin(r"SchemaEngine\.Dialect\((?!;)", source)
            host = Module(Symbol(module_name, :Host))
            Base.include_string(host, source, string(module_name, ".jl"))
            generated_module = Base.invokelatest(getfield, host, module_name)
            spec = Base.invokelatest(getfield, generated_module, :_SPEC)
            graph = Base.invokelatest(OpenAPI.Runtime._schema_graph, spec)
            dialects = collect(values(getfield(graph.template, :dialects)))
            custom = only(filter(dialect -> dialect.uri == dialect_uri, dialects))
            @test custom.validation === false
            @test custom.applicator === false
        end
    end

    @testset "model and field docstrings from spec descriptions" begin
        pet_doc = "    Pet\n\nA pet in the store.\n\n" *
                  "- `name`: The pet's display name.\n- `status`: Adoption status."
        @test occursin("@doc " * repr(pet_doc), client_source)
        @test occursin("@doc " * repr("    Status\n\nAdoption status."), client_source)
        @test occursin("@doc " * repr(pet_doc), server_source)

        operation_doc = "    getpet(...)\n\n`GET /pets/{petId}`\n\n" *
                        "- `petid`: Numeric pet identifier."
        @test occursin("@doc " * repr(operation_doc), client_source)

        host = Module(:ContractDocsHost)
        Base.include_string(host, client_source, "ContractClient.jl")
        C = Base.invokelatest(getfield, host, :ContractClient)
        binding = Base.invokelatest(Base.Docs.Binding, C, :Pet)
        meta = Base.invokelatest(Base.Docs.meta, C)
        @test haskey(meta, binding)
        attached = join(
            (string(text) for docstr in values(meta[binding].docs)
             for text in docstr.text),
            "\n",
        )
        @test occursin("A pet in the store.", attached)
        @test occursin("The pet's display name.", attached)
    end
end
