# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_echo_post_request

    EchoPostRequest(;
        data=nothing,
    )

    - data::String : Data to echo back
"""
Base.@kwdef mutable struct EchoPostRequest <: OpenAPI.APIModel
    data::Union{Nothing, String} = nothing

    function EchoPostRequest(data, )
        o = new(data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EchoPostRequest

const _property_types_EchoPostRequest = Dict{Symbol,String}(Symbol("data")=>"String", )
OpenAPI.property_type(::Type{ EchoPostRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EchoPostRequest[name]))}

function OpenAPI.check_required(o::EchoPostRequest)
    true
end

function OpenAPI.validate_properties(o::EchoPostRequest)
    OpenAPI.validate_property(EchoPostRequest, Symbol("data"), o.data)
end

function OpenAPI.validate_property(::Type{ EchoPostRequest }, name::Symbol, val)

end
