# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_echo_get_200_response

    EchoGet200Response(;
        timestamp=nothing,
        message=nothing,
    )

    - timestamp::ZonedDateTime : Server timestamp when request was received
    - message::String : Echo message
"""
Base.@kwdef mutable struct EchoGet200Response <: OpenAPI.APIModel
    timestamp::Union{Nothing, ZonedDateTime} = nothing
    message::Union{Nothing, String} = nothing

    function EchoGet200Response(timestamp, message, )
        o = new(timestamp, message, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EchoGet200Response

const _property_types_EchoGet200Response = Dict{Symbol,String}(Symbol("timestamp")=>"ZonedDateTime", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ EchoGet200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EchoGet200Response[name]))}

function OpenAPI.check_required(o::EchoGet200Response)
    true
end

function OpenAPI.validate_properties(o::EchoGet200Response)
    OpenAPI.validate_property(EchoGet200Response, Symbol("timestamp"), o.timestamp)
    OpenAPI.validate_property(EchoGet200Response, Symbol("message"), o.message)
end

function OpenAPI.validate_property(::Type{ EchoGet200Response }, name::Symbol, val)

    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "EchoGet200Response", :format, val, "date-time")
    end

end
