# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_echo_post_200_response

    EchoPost200Response(;
        timestamp=nothing,
        data=nothing,
    )

    - timestamp::ZonedDateTime : Server timestamp when request was received
    - data::String : Echoed data from request
"""
Base.@kwdef mutable struct EchoPost200Response <: OpenAPI.APIModel
    timestamp::Union{Nothing, ZonedDateTime} = nothing
    data::Union{Nothing, String} = nothing

    function EchoPost200Response(timestamp, data, )
        o = new(timestamp, data, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EchoPost200Response

const _property_types_EchoPost200Response = Dict{Symbol,String}(Symbol("timestamp")=>"ZonedDateTime", Symbol("data")=>"String", )
OpenAPI.property_type(::Type{ EchoPost200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EchoPost200Response[name]))}

function OpenAPI.check_required(o::EchoPost200Response)
    true
end

function OpenAPI.validate_properties(o::EchoPost200Response)
    OpenAPI.validate_property(EchoPost200Response, Symbol("timestamp"), o.timestamp)
    OpenAPI.validate_property(EchoPost200Response, Symbol("data"), o.data)
end

function OpenAPI.validate_property(::Type{ EchoPost200Response }, name::Symbol, val)

    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "EchoPost200Response", :format, val, "date-time")
    end

end
