# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


function file_upload_finalize_read(handler)
    function file_upload_finalize_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        openapi_params["UploadFileDetails"] = OpenAPI.Servers.to_param_type(UploadFileDetails, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function file_upload_finalize_validate(handler)
    function file_upload_finalize_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "file_upload_finalize", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "file_upload_finalize", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function file_upload_finalize_invoke(impl; post_invoke=nothing)
    function file_upload_finalize_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.file_upload_finalize(req::HTTP.Request, openapi_params["job_id"], openapi_params["UploadFileDetails"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function file_upload_init_read(handler)
    function file_upload_init_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        openapi_params["UploadFileDetails"] = OpenAPI.Servers.to_param_type(UploadFileDetails, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function file_upload_init_validate(handler)
    function file_upload_init_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "file_upload_init", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "file_upload_init", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function file_upload_init_invoke(impl; post_invoke=nothing)
    function file_upload_init_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.file_upload_init(req::HTTP.Request, openapi_params["job_id"], openapi_params["UploadFileDetails"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_clusterinfo_read(handler)
    function get_clusterinfo_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_clusterinfo_validate(handler)
    function get_clusterinfo_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "get_clusterinfo", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "get_clusterinfo", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function get_clusterinfo_invoke(impl; post_invoke=nothing)
    function get_clusterinfo_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_clusterinfo(req::HTTP.Request, openapi_params["job_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_dataset_credentials_read(handler)
    function get_dataset_credentials_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["dataset_id"] = OpenAPI.Servers.to_param(String, path_params, "dataset_id", required=true, )
        headers = Dict{String,String}(req.headers)
        openapi_params["X-JuliaHub-JobId"] = OpenAPI.Servers.to_param(String, headers, "X-JuliaHub-JobId", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_dataset_credentials_validate(handler)
    function get_dataset_credentials_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("dataset_id", "get_dataset_credentials", :maxLength, openapi_params["dataset_id"], 36)
        OpenAPI.validate_param("dataset_id", "get_dataset_credentials", :minLength, openapi_params["dataset_id"], 36)
        
        OpenAPI.validate_param("X-JuliaHub-JobId", "get_dataset_credentials", :maxLength, openapi_params["X-JuliaHub-JobId"], 13)
        OpenAPI.validate_param("X-JuliaHub-JobId", "get_dataset_credentials", :minLength, openapi_params["X-JuliaHub-JobId"], 10)
        
        return handler(req)
    end
end

function get_dataset_credentials_invoke(impl; post_invoke=nothing)
    function get_dataset_credentials_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_dataset_credentials(req::HTTP.Request, openapi_params["dataset_id"], openapi_params["X-JuliaHub-JobId"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_datasets_read(handler)
    function get_datasets_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_datasets_validate(handler)
    function get_datasets_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_datasets_invoke(impl; post_invoke=nothing)
    function get_datasets_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_datasets(req::HTTP.Request;)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_job_input_read(handler)
    function get_job_input_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_job_input_validate(handler)
    function get_job_input_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "get_job_input", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "get_job_input", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function get_job_input_invoke(impl; post_invoke=nothing)
    function get_job_input_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_job_input(req::HTTP.Request, openapi_params["job_id"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_user_datasets_read(handler)
    function get_user_datasets_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        query_params = HTTP.queryparams(URIs.URI(req.target))
        openapi_params["name"] = OpenAPI.Servers.to_param(String, query_params, "name", style="form", is_explode=true)
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_user_datasets_validate(handler)
    function get_user_datasets_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        
        return handler(req)
    end
end

function get_user_datasets_invoke(impl; post_invoke=nothing)
    function get_user_datasets_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_user_datasets(req::HTTP.Request; name=get(openapi_params, "name", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function update_job_distributed_status_read(handler)
    function update_job_distributed_status_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        openapi_params["JobDistributedStatus"] = OpenAPI.Servers.to_param_type(JobDistributedStatus, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function update_job_distributed_status_validate(handler)
    function update_job_distributed_status_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "update_job_distributed_status", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "update_job_distributed_status", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function update_job_distributed_status_invoke(impl; post_invoke=nothing)
    function update_job_distributed_status_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.update_job_distributed_status(req::HTTP.Request, openapi_params["job_id"], openapi_params["JobDistributedStatus"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function update_job_status_read(handler)
    function update_job_status_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["job_id"] = OpenAPI.Servers.to_param(String, path_params, "job_id", required=true, )
        openapi_params["JobStatus"] = OpenAPI.Servers.to_param_type(JobStatus, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function update_job_status_validate(handler)
    function update_job_status_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("job_id", "update_job_status", :maxLength, openapi_params["job_id"], 13)
        OpenAPI.validate_param("job_id", "update_job_status", :minLength, openapi_params["job_id"], 10)
        
        return handler(req)
    end
end

function update_job_status_invoke(impl; post_invoke=nothing)
    function update_job_status_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.update_job_status(req::HTTP.Request, openapi_params["job_id"], openapi_params["JobStatus"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerJobRunnerApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "POST", path_prefix * "/jobs/{job_id}/file_uploads", OpenAPI.Servers.middleware(impl, file_upload_finalize_read, file_upload_finalize_validate, file_upload_finalize_invoke; optional_middlewares...))
    HTTP.register!(router, "PUT", path_prefix * "/jobs/{job_id}/file_uploads", OpenAPI.Servers.middleware(impl, file_upload_init_read, file_upload_init_validate, file_upload_init_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/jobs/{job_id}/clusterinfo", OpenAPI.Servers.middleware(impl, get_clusterinfo_read, get_clusterinfo_validate, get_clusterinfo_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/datasets/{dataset_id}/credentials", OpenAPI.Servers.middleware(impl, get_dataset_credentials_read, get_dataset_credentials_validate, get_dataset_credentials_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/datasets", OpenAPI.Servers.middleware(impl, get_datasets_read, get_datasets_validate, get_datasets_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/jobs/{job_id}/input", OpenAPI.Servers.middleware(impl, get_job_input_read, get_job_input_validate, get_job_input_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/user/datasets", OpenAPI.Servers.middleware(impl, get_user_datasets_read, get_user_datasets_validate, get_user_datasets_invoke; optional_middlewares...))
    HTTP.register!(router, "POST", path_prefix * "/jobs/{job_id}/distributed_status", OpenAPI.Servers.middleware(impl, update_job_distributed_status_read, update_job_distributed_status_validate, update_job_distributed_status_invoke; optional_middlewares...))
    HTTP.register!(router, "POST", path_prefix * "/jobs/{job_id}/status", OpenAPI.Servers.middleware(impl, update_job_status_read, update_job_status_validate, update_job_status_invoke; optional_middlewares...))
    return router
end
