# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


function delete_document_read(handler)
    function delete_document_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function delete_document_validate(handler)
    function delete_document_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function delete_document_invoke(impl; post_invoke=nothing)
    function delete_document_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.delete_document(req::HTTP.Request, openapi_params["path"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_document_read(handler)
    function get_document_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        query_params = HTTP.queryparams(URIs.URI(req.target))
        openapi_params["input"] = OpenAPI.Servers.to_param(Dict{String, Any}, query_params, "input", )
        openapi_params["pretty"] = OpenAPI.Servers.to_param(Bool, query_params, "pretty", )
        openapi_params["provenance"] = OpenAPI.Servers.to_param(Bool, query_params, "provenance", )
        openapi_params["explain"] = OpenAPI.Servers.to_param(String, query_params, "explain", )
        openapi_params["metrics"] = OpenAPI.Servers.to_param(Bool, query_params, "metrics", )
        openapi_params["instrument"] = OpenAPI.Servers.to_param(Bool, query_params, "instrument", )
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_document_validate(handler)
    function get_document_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_document_invoke(impl; post_invoke=nothing)
    function get_document_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_document(req::HTTP.Request, openapi_params["path"]; input=get(openapi_params, "input", nothing), pretty=get(openapi_params, "pretty", nothing), provenance=get(openapi_params, "provenance", nothing), explain=get(openapi_params, "explain", nothing), metrics=get(openapi_params, "metrics", nothing), instrument=get(openapi_params, "instrument", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_document_with_path_read(handler)
    function get_document_with_path_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        query_params = HTTP.queryparams(URIs.URI(req.target))
        openapi_params["pretty"] = OpenAPI.Servers.to_param(Bool, query_params, "pretty", )
        openapi_params["provenance"] = OpenAPI.Servers.to_param(Bool, query_params, "provenance", )
        openapi_params["explain"] = OpenAPI.Servers.to_param(String, query_params, "explain", )
        openapi_params["metrics"] = OpenAPI.Servers.to_param(Bool, query_params, "metrics", )
        openapi_params["instrument"] = OpenAPI.Servers.to_param(Bool, query_params, "instrument", )
        openapi_params["request_body"] = OpenAPI.Servers.to_param_type(Dict{String, Any}, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_document_with_path_validate(handler)
    function get_document_with_path_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_document_with_path_invoke(impl; post_invoke=nothing)
    function get_document_with_path_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_document_with_path(req::HTTP.Request, openapi_params["path"], openapi_params["request_body"]; pretty=get(openapi_params, "pretty", nothing), provenance=get(openapi_params, "provenance", nothing), explain=get(openapi_params, "explain", nothing), metrics=get(openapi_params, "metrics", nothing), instrument=get(openapi_params, "instrument", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function get_document_with_web_hook_read(handler)
    function get_document_with_web_hook_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        query_params = HTTP.queryparams(URIs.URI(req.target))
        openapi_params["pretty"] = OpenAPI.Servers.to_param(Bool, query_params, "pretty", )
        openapi_params["request_body"] = OpenAPI.Servers.to_param_type(Dict{String, Any}, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function get_document_with_web_hook_validate(handler)
    function get_document_with_web_hook_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function get_document_with_web_hook_invoke(impl; post_invoke=nothing)
    function get_document_with_web_hook_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.get_document_with_web_hook(req::HTTP.Request, openapi_params["path"], openapi_params["request_body"]; pretty=get(openapi_params, "pretty", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function patch_document_read(handler)
    function patch_document_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        openapi_params["PatchesSchemaInner"] = OpenAPI.Servers.to_param_type(Vector{PatchesSchemaInner}, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function patch_document_validate(handler)
    function patch_document_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        OpenAPI.validate_param("PatchesSchemaInner", "patch_document", :minItems, openapi_params["PatchesSchemaInner"], 1)
        
        return handler(req)
    end
end

function patch_document_invoke(impl; post_invoke=nothing)
    function patch_document_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.patch_document(req::HTTP.Request, openapi_params["path"], openapi_params["PatchesSchemaInner"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end

function put_document_read(handler)
    function put_document_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        path_params = HTTP.getparams(req)
        openapi_params["path"] = OpenAPI.Servers.to_param(String, path_params, "path", required=true, )
        headers = Dict{String,String}(req.headers)
        openapi_params["If-None-Match"] = OpenAPI.Servers.to_param(String, headers, "If-None-Match", )
        openapi_params["body"] = OpenAPI.Servers.to_param_type(Any, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function put_document_validate(handler)
    function put_document_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function put_document_invoke(impl; post_invoke=nothing)
    function put_document_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.put_document(req::HTTP.Request, openapi_params["path"], openapi_params["body"]; if_none_match=get(openapi_params, "If-None-Match", nothing),)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerDataAPIApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "DELETE", path_prefix * "/v1/data/{path}", OpenAPI.Servers.middleware(impl, delete_document_read, delete_document_validate, delete_document_invoke; optional_middlewares...))
    HTTP.register!(router, "GET", path_prefix * "/v1/data/{path}", OpenAPI.Servers.middleware(impl, get_document_read, get_document_validate, get_document_invoke; optional_middlewares...))
    HTTP.register!(router, "POST", path_prefix * "/v1/data/{path}", OpenAPI.Servers.middleware(impl, get_document_with_path_read, get_document_with_path_validate, get_document_with_path_invoke; optional_middlewares...))
    HTTP.register!(router, "POST", path_prefix * "/v0/data/{path}", OpenAPI.Servers.middleware(impl, get_document_with_web_hook_read, get_document_with_web_hook_validate, get_document_with_web_hook_invoke; optional_middlewares...))
    HTTP.register!(router, "PATCH", path_prefix * "/v1/data/{path}", OpenAPI.Servers.middleware(impl, patch_document_read, patch_document_validate, patch_document_invoke; optional_middlewares...))
    HTTP.register!(router, "PUT", path_prefix * "/v1/data/{path}", OpenAPI.Servers.middleware(impl, put_document_read, put_document_validate, put_document_invoke; optional_middlewares...))
    return router
end
