# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct DefaultApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `DefaultApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ DefaultApi }) = "http://localhost"

const _returntypes_test_DefaultApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => TestModel,
)

function _oacinternal_test(_api::DefaultApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_test_DefaultApi, "/test", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Test

Params:

Return: TestModel, OpenAPI.Clients.ApiResponse
"""
function test(_api::DefaultApi; _mediaType=nothing)
    _ctx = _oacinternal_test(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function test(_api::DefaultApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_test(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export test
