# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

include("models/model_AnyOfBaseType.jl")
include("models/model_AnyOfMappedPets.jl")
include("models/model_AnyOfPets.jl")
include("models/model_Cat.jl")
include("models/model_Dog.jl")
include("models/model_OneOfBaseType.jl")
include("models/model_OneOfMappedPets.jl")
include("models/model_OneOfPets.jl")
include("models/model_Pet.jl")
include("models/model_TypeWithAllArrayTypes.jl")
