# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""OneOfBaseType

    OneOfBaseType(; value=nothing)
"""
mutable struct OneOfBaseType <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Float64, String }
    OneOfBaseType() = new()
    OneOfBaseType(value) = new(value)
end # type OneOfBaseType

function OpenAPI.property_type(::Type{ OneOfBaseType }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(OneOfBaseType, name)
end
