# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TestResponse

    TestResponse(;
        message=nothing,
    )

    - message::String
"""
Base.@kwdef mutable struct TestResponse <: OpenAPI.APIModel
    message::Union{Nothing, String} = nothing

    function TestResponse(message, )
        OpenAPI.validate_property(TestResponse, Symbol("message"), message)
        return new(message, )
    end
end # type TestResponse

const _property_types_TestResponse = Dict{Symbol,String}(Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ TestResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TestResponse[name]))}

function check_required(o::TestResponse)
    true
end

function OpenAPI.validate_property(::Type{ TestResponse }, name::Symbol, val)
end
