# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct DefaultApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `DefaultApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ DefaultApi }) = "http://127.0.0.1:8082"

const _returntypes_echo_get_DefaultApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => EchoGet200Response,
)

function _oacinternal_echo_get(_api::DefaultApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_echo_get_DefaultApi, "/echo", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Echo GET endpoint

Returns a simple JSON response with server timestamp

Params:

Return: EchoGet200Response, OpenAPI.Clients.ApiResponse
"""
function echo_get(_api::DefaultApi; _mediaType=nothing)
    _ctx = _oacinternal_echo_get(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function echo_get(_api::DefaultApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_echo_get(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_echo_post_DefaultApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => EchoPost200Response,
)

function _oacinternal_echo_post(_api::DefaultApi, echo_post_request::EchoPostRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_echo_post_DefaultApi, "/echo", [], echo_post_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Echo POST endpoint

Echoes back the request body with metadata

Params:
- echo_post_request::EchoPostRequest (required)

Return: EchoPost200Response, OpenAPI.Clients.ApiResponse
"""
function echo_post(_api::DefaultApi, echo_post_request::EchoPostRequest; _mediaType=nothing)
    _ctx = _oacinternal_echo_post(_api, echo_post_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function echo_post(_api::DefaultApi, response_stream::Channel, echo_post_request::EchoPostRequest; _mediaType=nothing)
    _ctx = _oacinternal_echo_post(_api, echo_post_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export echo_get
export echo_post
