# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""findPetsByStatus_status_parameter

    FindPetsByStatusStatusParameter(;
        name=nothing,
        statuses=nothing,
    )

    - name::String
    - statuses::Vector{String}
"""
Base.@kwdef mutable struct FindPetsByStatusStatusParameter <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    statuses::Union{Nothing, Vector{String}} = nothing

    function FindPetsByStatusStatusParameter(name, statuses, )
        OpenAPI.validate_property(FindPetsByStatusStatusParameter, Symbol("name"), name)
        OpenAPI.validate_property(FindPetsByStatusStatusParameter, Symbol("statuses"), statuses)
        return new(name, statuses, )
    end
end # type FindPetsByStatusStatusParameter

const _property_types_FindPetsByStatusStatusParameter = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("statuses")=>"Vector{String}", )
OpenAPI.property_type(::Type{ FindPetsByStatusStatusParameter }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FindPetsByStatusStatusParameter[name]))}

function check_required(o::FindPetsByStatusStatusParameter)
    true
end

function OpenAPI.validate_property(::Type{ FindPetsByStatusStatusParameter }, name::Symbol, val)
end
