# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct DefaultApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `DefaultApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ DefaultApi }) = "http://localhost"

const _returntypes_delayresponse_get_DefaultApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DelayresponseGet200Response,
)

function _oacinternal_delayresponse_get(_api::DefaultApi, delay_seconds::Int64; _mediaType=nothing)
    OpenAPI.validate_param("delay_seconds", "delayresponse_get", :minimum, delay_seconds, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_delayresponse_get_DefaultApi, "/delayresponse", [])
    OpenAPI.Clients.set_param(_ctx.query, "delay_seconds", delay_seconds)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Delay Response Endpoint

Params:
- delay_seconds::Int64 (required)

Return: DelayresponseGet200Response, OpenAPI.Clients.ApiResponse
"""
function delayresponse_get(_api::DefaultApi, delay_seconds::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delayresponse_get(_api, delay_seconds; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delayresponse_get(_api::DefaultApi, response_stream::Channel, delay_seconds::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delayresponse_get(_api, delay_seconds; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export delayresponse_get
