# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PetApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PetApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PetApi }) = "http://petstore.swagger.io/v2"

const _returntypes_find_pets_by_status_PetApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => FindPetsByStatus200Response,
    Regex("^" * replace("400", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_find_pets_by_status(_api::PetApi, status::FindPetsByStatusStatusParameter; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_find_pets_by_status_PetApi, "/pet/findByStatus", [])
    OpenAPI.Clients.set_param(_ctx.query, "status", status; style="deepObject", location=:query, is_explode=true)  # type FindPetsByStatusStatusParameter
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Finds Pets by status

Multiple status values can be provided with comma separated strings

Params:
- status::FindPetsByStatusStatusParameter (required)

Return: FindPetsByStatus200Response, OpenAPI.Clients.ApiResponse
"""
function find_pets_by_status(_api::PetApi, status::FindPetsByStatusStatusParameter; _mediaType=nothing)
    _ctx = _oacinternal_find_pets_by_status(_api, status; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function find_pets_by_status(_api::PetApi, response_stream::Channel, status::FindPetsByStatusStatusParameter; _mediaType=nothing)
    _ctx = _oacinternal_find_pets_by_status(_api, status; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export find_pets_by_status
