# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    FindPetsByStatusStatusParameterStatusesInnerInner(;
        type=nothing,
    )

    - type::String
"""
Base.@kwdef mutable struct FindPetsByStatusStatusParameterStatusesInnerInner <: OpenAPI.APIModel
    type::Union{Nothing, String} = nothing

    function FindPetsByStatusStatusParameterStatusesInnerInner(type, )
        OpenAPI.validate_property(FindPetsByStatusStatusParameterStatusesInnerInner, Symbol("type"), type)
        return new(type, )
    end
end # type FindPetsByStatusStatusParameterStatusesInnerInner

const _property_types_FindPetsByStatusStatusParameterStatusesInnerInner = Dict{Symbol,String}(Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ FindPetsByStatusStatusParameterStatusesInnerInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FindPetsByStatusStatusParameterStatusesInnerInner[name]))}

function check_required(o::FindPetsByStatusStatusParameterStatusesInnerInner)
    true
end

function OpenAPI.validate_property(::Type{ FindPetsByStatusStatusParameterStatusesInnerInner }, name::Symbol, val)
end
