# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

include("model_ApiResponse.jl")
include("model_Category.jl")
include("model_Order.jl")
include("model_Pet.jl")
include("model_Tag.jl")
include("model_User.jl")
