# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Category
A category for a pet

    Category(;
        name=nothing,
        id=nothing,
    )

    - name::String
    - id::Int64
"""
Base.@kwdef mutable struct Category <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    id::Union{Nothing, Int64} = nothing

    function Category(name, id, )
        OpenAPI.validate_property(Category, Symbol("name"), name)
        OpenAPI.validate_property(Category, Symbol("id"), id)
        return new(name, id, )
    end
end # type Category

const _property_types_Category = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ Category }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Category[name]))}

function check_required(o::Category)
    true
end

function OpenAPI.validate_property(::Type{ Category }, name::Symbol, val)
    if name === Symbol("name")
        OpenAPI.validate_param(name, "Category", :pattern, val, r"^[a-zA-Z0-9]+[a-zA-Z0-9\.\-_]*[a-zA-Z0-9]+$")
    end
    if name === Symbol("id")
        OpenAPI.validate_param(name, "Category", :format, val, "int64")
    end
end
