# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_delayresponse_get_200_response

    DelayresponseGet200Response(;
        delay_seconds=nothing,
    )

    - delay_seconds::String
"""
Base.@kwdef mutable struct DelayresponseGet200Response <: OpenAPI.APIModel
    delay_seconds::Union{Nothing, String} = nothing

    function DelayresponseGet200Response(delay_seconds, )
        OpenAPI.validate_property(DelayresponseGet200Response, Symbol("delay_seconds"), delay_seconds)
        return new(delay_seconds, )
    end
end # type DelayresponseGet200Response

const _property_types_DelayresponseGet200Response = Dict{Symbol,String}(Symbol("delay_seconds")=>"String", )
OpenAPI.property_type(::Type{ DelayresponseGet200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DelayresponseGet200Response[name]))}

function check_required(o::DelayresponseGet200Response)
    true
end

function OpenAPI.validate_property(::Type{ DelayresponseGet200Response }, name::Symbol, val)
end
