# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""
    OneOfMappedPets(; value=nothing)
"""
mutable struct OneOfMappedPets <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Cat, Dog }
    OneOfMappedPets() = new()
    OneOfMappedPets(value) = new(value)
end # type OneOfMappedPets

function OpenAPI.property_type(::Type{ OneOfMappedPets }, name::Symbol, json::Dict{String,Any})
    discriminator = json["pet_type"]
    if discriminator == "cat"
        return eval(Base.Meta.parse("Cat"))
    elseif discriminator == "dog"
        return eval(Base.Meta.parse("Dog"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for OneOfMappedPets"))
end
