# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""AnyOfBaseType

    AnyOfBaseType(; value=nothing)
"""
mutable struct AnyOfBaseType <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    AnyOfBaseType() = new()
    AnyOfBaseType(value) = new(value)
end # type AnyOfBaseType

function OpenAPI.property_type(::Type{ AnyOfBaseType }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(AnyOfBaseType, name)
end
