# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Cat

    Cat(;
        pet_type=nothing,
        hunts=nothing,
        age=nothing,
    )

    - pet_type::String
    - hunts::Bool
    - age::Int64
"""
Base.@kwdef mutable struct Cat <: OpenAPI.APIModel
    pet_type::Union{Nothing, String} = nothing
    hunts::Union{Nothing, Bool} = nothing
    age::Union{Nothing, Int64} = nothing

    function Cat(pet_type, hunts, age, )
        OpenAPI.validate_property(Cat, Symbol("pet_type"), pet_type)
        OpenAPI.validate_property(Cat, Symbol("hunts"), hunts)
        OpenAPI.validate_property(Cat, Symbol("age"), age)
        return new(pet_type, hunts, age, )
    end
end # type Cat

const _property_types_Cat = Dict{Symbol,String}(Symbol("pet_type")=>"String", Symbol("hunts")=>"Bool", Symbol("age")=>"Int64", )
OpenAPI.property_type(::Type{ Cat }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Cat[name]))}

function check_required(o::Cat)
    o.pet_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Cat }, name::Symbol, val)
end
