# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""AnyOfMappedPets

    AnyOfMappedPets(; value=nothing)
"""
mutable struct AnyOfMappedPets <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Cat, Dog }
    AnyOfMappedPets() = new()
    AnyOfMappedPets(value) = new(value)
end # type AnyOfMappedPets

function OpenAPI.property_type(::Type{ AnyOfMappedPets }, name::Symbol, json::Dict{String,Any})
    discriminator = json["pet_type"]
    if discriminator == "cat"
        return eval(Base.Meta.parse("Cat"))
    elseif discriminator == "dog"
        return eval(Base.Meta.parse("Dog"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for AnyOfMappedPets"))
end
