# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    CatAllOf(;
        hunts=nothing,
        age=nothing,
    )

    - hunts::Bool
    - age::Int64
"""
Base.@kwdef mutable struct CatAllOf <: OpenAPI.APIModel
    hunts::Union{Nothing, Bool} = nothing
    age::Union{Nothing, Int64} = nothing

    function CatAllOf(hunts, age, )
        OpenAPI.validate_property(CatAllOf, Symbol("hunts"), hunts)
        OpenAPI.validate_property(CatAllOf, Symbol("age"), age)
        return new(hunts, age, )
    end
end # type CatAllOf

const _property_types_CatAllOf = Dict{Symbol,String}(Symbol("hunts")=>"Bool", Symbol("age")=>"Int64", )
OpenAPI.property_type(::Type{ CatAllOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CatAllOf[name]))}

function check_required(o::CatAllOf)
    true
end

function OpenAPI.validate_property(::Type{ CatAllOf }, name::Symbol, val)
end
