# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""OneOfPets

    OneOfPets(; value=nothing)
"""
mutable struct OneOfPets <: OpenAPI.OneOfAPIModel
    value::Any # Union{ Cat, Dog }
    OneOfPets() = new()
    OneOfPets(value) = new(value)
end # type OneOfPets

function OpenAPI.property_type(::Type{ OneOfPets }, name::Symbol, json::Dict{String,Any})
    discriminator = json["pet_type"]
    if discriminator == "Cat"
        return eval(Base.Meta.parse("Cat"))
    elseif discriminator == "Dog"
        return eval(Base.Meta.parse("Dog"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for OneOfPets"))
end

