# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""AnyOfPets

    AnyOfPets(; value=nothing)
"""
mutable struct AnyOfPets <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Cat, Dog }
    AnyOfPets() = new()
    AnyOfPets(value) = new(value)
end # type AnyOfPets

function OpenAPI.property_type(::Type{ AnyOfPets }, name::Symbol, json::Dict{String,Any})
    discriminator = json["pet_type"]
    if discriminator == "Cat"
        return eval(Base.Meta.parse("Cat"))
    elseif discriminator == "Dog"
        return eval(Base.Meta.parse("Dog"))
    end
    throw(OpenAPI.ValidationException("Invalid discriminator value: $discriminator for AnyOfPets"))
end

